---
- name: Ensure redislabs user/groups exist
  hosts: redis
  become: yes
  become_user: root
  tasks:
    - name: Ensure redislabs group exists
      group:
        name: redislabs
        state: present
    - name: Ensure redislabs user exists
      user: name=redislabs state=present groups=redislabs append=yes 

- name: Ensure redis required packages are installed
  hosts: redis
  become: yes
  become_user: root
  tasks:
    - name: Ensure redis required packages are installed
      apt:
        update-cache: yes
        name: 
          - make
          - gcc
          - pkg-config
          - libsystemd-dev
        state: latest

- name: Copy Redis files and unpack
  hosts: redis
  become: yes
  become_user: root
  tasks:
    - name: Ensure destination path exists
      file:
        path: /root/redis
        state: directory
    - name: download latest redis version
      get_url:
        dest: /root/redis
        url: https://download.redis.io/redis-stable.tar.gz
    - name: Ensure redis files are extracted
      unarchive:
        src: /root/redis/redis-stable.tar.gz
        dest: /root/redis
        remote_src: yes
        creates: /root/redis/redis-stable
    - name: redis install script run
      shell: cd /root/redis/redis-stable && make BUILD_WITH_SYSTEMD=yes USE_SYSTEMD=yes && make install creates=/usr/local/bin/redis-server
    - name: copy redis service to systemd
      copy:
        src: /root/redis/redis-stable/utils/systemd-redis_server.service
        dest: /etc/systemd/system/redis.service
        remote_src: yes
    - name: start redis server service
      service:
        name: redis
        enabled: yes
        state: started

- name: ensure redis is accepting connections
  hosts: redis
  become: yes
  become_user: root
  tasks:
    - name: ping redis locally
      command: redis-cli ping
    